# Generated by Django 5.2.2 on 2025-06-08 19:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postknob', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostKnob',
            new_name='Post',
        ),
    ]
