[pytest]
DJANGO_SETTINGS_MODULE = postapp.settings.dev
python_files = tests/test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --no-header -rN
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
